name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y  build-essential automake autoconf flex check llvm-dev pkg-config zlib1g-dev libdw-dev libffi-dev libzstd-dev pkgconf

      - name: compile local nvc
        run: |
          wget -c https://github.com/nickg/nvc/releases/download/r1.21.0/nvc-1.21.0.tar.gz -O - | tar -xz
          pwd
          sudo apt-get install -y  build-essential automake autoconf flex check llvm-dev pkg-config zlib1g-dev libdw-dev libffi-dev libzstd-dev pkgconf
          cd nvc-1.21.0 && mkdir build && cd build
          ../configure
          make

      - name: Test main repo
        run: bazel test //...

      - name: Test e2e/minimal_example
        working-directory: e2e/minimal_example
        run: bazel test //...

      - name: Test e2e/simple_example
        working-directory: e2e/simple_example
        run: bazel test //...

      - name: Test e2e/custom_py_deps
        working-directory: e2e/custom_py_deps
        run: bazel test //...
